Update tether
Added Kitty as a terminal option in setup()

diff --git a/tether b/tether
--- a/tether
+++ b/tether
@@ -27,7 +27,7 @@
 # Check if bash version is >= 5
 #--------------------------------------------------------------
 [[ ${BASH_VERSINFO[0]} -lt 5 ]] && {
-	echo -e "\033[1;37m[\033[1;31m-\033[1;37m] Bash version 5.0 or later is required \033[00m"
+	echo -e "\033[1;97m[\033[1;31m-\033[1;97m] Bash version 5.0 or later is required \033[00m"
 	exit 1
 }
 
@@ -39,7 +39,7 @@ script_name="${0##*/}"
 #--------------------------------------------------------------
 # Set the version of this script
 #--------------------------------------------------------------
-script_version="23.12.10.0335"
+script_version="23.12.12.1443"
 
 #--------------------------------------------------------------
 # Set variables if running on Android
@@ -100,21 +100,21 @@ cpu_core_count="$((cpu_core_count + 1))"
 # Print out error message
 #--------------------------------------------------------------
 print_error(){
-	echo -e "\033[1;37m[\033[1;31m-\033[1;37m] $@ \033[00m"
+	echo -e "\033[1;97m[\033[1;31m-\033[1;97m] $@ \033[00m"
 }
 
 #--------------------------------------------------------------
 # Print out success message
 #--------------------------------------------------------------
 print_success(){
-	echo -e "\033[1;37m[\033[1;32m+\033[1;37m] $@ \033[00m"
+	echo -e "\033[1;97m[\033[1;32m+\033[1;97m] $@ \033[00m"
 }
 
 #--------------------------------------------------------------
 # Print out warning/notice
 #--------------------------------------------------------------
 print_warning(){
-	echo -e "\033[1;37m[\033[1;35m*\033[1;37m] $@ \033[00m"
+	echo -e "\033[1;97m[\033[1;35m*\033[1;97m] $@ \033[00m"
 }
 
 #--------------------------------------------------------------
@@ -324,7 +324,7 @@ print_usage_bar(){
 	color_red="\033[1;31m"
 	color_green="\033[1;32m"
 	color_yellow="\033[1;33m"
-	color_white="\033[1;37m"
+	color_white="\033[1;97m"
 	# Reduce $usage_visualizer value to reduce runtime
 	usage_counter="$(( usage_visualizer / 5 ))"
 	# Handles all $usage_visualizer values > 0
@@ -504,7 +504,7 @@ blue="\[\e[1;34m\]"
 yellow="\[\e[1;33m\]"
 magenta="\[\e[1;35m\]"
 cyan="\[\e[1;36m\]"
-white="\[\e[1;37m\]"
+white="\[\e[1;97m\]"
 none="\[\e[00m\]"
 	
 # Handles Android
@@ -808,30 +808,174 @@ pp(){
 }
 
 [[ $USER == "root" ]] && {
-	PS1=$'\e[1;37m┌─[\e[1;35m$(date +%H:%M:%S)\e[1;37m] [\e[1;35m$HOSTNAME@$USER\e[1;37m] [\e[1;32m$PWD\e[1;37m]\n\e[1;37m╰──\e[0m \e[1;33m$\e[0m '
-	PS2=$'\e[1;37m┌─[\e[1;35m'
+	PS1=$'\e[1;97m┌─[\e[1;35m$(date +%H:%M:%S)\e[1;97m] [\e[1;35m$HOSTNAME@$USER\e[1;97m] [\e[1;32m$PWD\e[1;97m]\n\e[1;97m╰──\e[0m \e[1;33m$\e[0m '
+	PS2=$'\e[1;97m┌─[\e[1;35m'
 	PS2+="$(date +%H:%M:%S)"
-	PS2+=$'\e[1;37m] [\e[1;35m'
+	PS2+=$'\e[1;97m] [\e[1;35m'
 	PS2+="$HOSTNAME@$USER"
-	PS2+=$'\e[1;37m]\n\e[1;37m╰──\e[0m \e[1;33m$\e[0m '
+	PS2+=$'\e[1;97m]\n\e[1;97m╰──\e[0m \e[1;33m$\e[0m '
 }
 [[ $USER == "shell" ]] && {
-	PS1=$'\e[1;37m┌─[\e[1;36m$(date +%H:%M:%S)\e[1;37m] [\e[1;36m$HOSTNAME@$USER\e[1;37m] [\e[1;32m$PWD\e[1;37m]\n\e[1;37m╰──\e[0m \e[1;33m$\e[0m '
-	PS2=$'\e[1;37m┌─[\e[1;36m'
+	PS1=$'\e[1;97m┌─[\e[1;36m$(date +%H:%M:%S)\e[1;97m] [\e[1;36m$HOSTNAME@$USER\e[1;97m] [\e[1;32m$PWD\e[1;97m]\n\e[1;97m╰──\e[0m \e[1;33m$\e[0m '
+	PS2=$'\e[1;97m┌─[\e[1;36m'
 	PS2+="$(date +%H:%M:%S)"
-	PS2+=$'\e[1;37m] [\e[1;36m'
+	PS2+=$'\e[1;97m] [\e[1;36m'
 	PS2+="$HOSTNAME@$USER"
-	PS2+=$'\e[1;37m]\n\e[1;37m╰──\e[0m \e[1;33m$\e[0m '
+	PS2+=$'\e[1;97m]\n\e[1;97m╰──\e[0m \e[1;33m$\e[0m '
 }
 [[ $USER != "root" && $USER != "shell" ]] && {
-	PS1=$'\e[1;37m┌─[\e[1;34m$(date +%H:%M:%S)\e[1;37m] [\e[1;34m$HOSTNAME@$USER\e[1;37m] [\e[1;32m$PWD\e[1;37m]\n\e[1;37m╰──\e[0m \e[1;33m$\e[0m '
-	PS2=$'\e[1;37m┌─[\e[1;34m'
+	PS1=$'\e[1;97m┌─[\e[1;34m$(date +%H:%M:%S)\e[1;97m] [\e[1;34m$HOSTNAME@$USER\e[1;97m] [\e[1;32m$PWD\e[1;97m]\n\e[1;97m╰──\e[0m \e[1;33m$\e[0m '
+	PS2=$'\e[1;97m┌─[\e[1;34m'
 	PS2+="$(date +%H:%M:%S)"
-	PS2+=$'\e[1;37m] [\e[1;34m'
+	PS2+=$'\e[1;97m] [\e[1;34m'
 	PS2+="$HOSTNAME@$USER"
-	PS2+=$'\e[1;37m]\n\e[1;37m╰──\e[0m \e[1;33m$\e[0m '
+	PS2+=$'\e[1;97m]\n\e[1;97m╰──\e[0m \e[1;33m$\e[0m '
 }
 EOF
+}
+
+#--------------------------------------------------------------
+# Create custom kitty.conf file
+#--------------------------------------------------------------
+print_kitty(){
+	mkdir -p "/home/"${SUDO_USER:=$USER}"/.config/kitty" 2>/dev/null
+	cat 2>/dev/null << "EOF" > /home/"${SUDO_USER:=$USER}"/.config/kitty/kitty.conf
+#--------------------------------------------------------------
+# Appearance settings
+#--------------------------------------------------------------
+# Font configuration
+#--------------------------------------------------------------
+font_family      Iosevka
+bold_font        Iosevka Bold
+bold_italic_font Iosevka Bold Italic
+italic_font      Iosevka Italic
+
+#--------------------------------------------------------------
+# Set default font size
+#--------------------------------------------------------------
+font_size 12.0
+
+#--------------------------------------------------------------
+# Enable font ligatures
+#--------------------------------------------------------------
+disable_ligatures never
+
+#--------------------------------------------------------------
+# Set cursor shape
+#--------------------------------------------------------------
+cursor_shape beam
+
+#--------------------------------------------------------------
+# Set cursor blink speed
+#--------------------------------------------------------------
+cursor_blink_interval 0.5
+
+#--------------------------------------------------------------
+# Never timeout cursor blinking
+#--------------------------------------------------------------
+cursor_stop_blinking_after 0
+
+#--------------------------------------------------------------
+# Set terminal scrollback buffer size
+#--------------------------------------------------------------
+scrollback_lines 25000
+
+#--------------------------------------------------------------
+# Set terminal size
+#--------------------------------------------------------------
+remember_window_size  no
+initial_window_width  1024
+initial_window_height 960
+
+#--------------------------------------------------------------
+# Disable confirm to close dialog
+#--------------------------------------------------------------
+confirm_os_window_close 0
+
+#--------------------------------------------------------------
+# Tether Kitty colorscheme
+#--------------------------------------------------------------
+# Set cursor color
+#--------------------------------------------------------------
+cursor #D9BB96
+
+#--------------------------------------------------------------
+# Set foreground, background color
+#--------------------------------------------------------------
+foreground            #D1B38F
+background            #060A0C
+selection_foreground  #060A0C
+selection_background  #D1B38F
+url_color             #72C2D6
+
+#--------------------------------------------------------------
+# High contrast blue/navy blue
+#--------------------------------------------------------------
+color0  #060A0C
+
+#--------------------------------------------------------------
+# Low contrast blue/navy blue
+#--------------------------------------------------------------
+color7  #121D23
+
+#--------------------------------------------------------------
+# Desaturated dark brown - Desaturated light brown
+#--------------------------------------------------------------
+color8  #D1B38F
+color15 #D9BB96
+
+#--------------------------------------------------------------
+# Desaturated Red
+#--------------------------------------------------------------
+color1  #FE5E41
+color9  #FE5E41
+
+#--------------------------------------------------------------
+# Desaturated Green
+#--------------------------------------------------------------
+color2  #B1CC72
+color10 #B1CC72
+
+#--------------------------------------------------------------
+# Desaturated Yellow
+#--------------------------------------------------------------
+color3  #FFAC54
+color11 #FFAC54
+
+#--------------------------------------------------------------
+# Desaturated Blue
+#--------------------------------------------------------------
+color4  #72C2D6
+color12 #72C2D6
+
+#--------------------------------------------------------------
+# Desaturated Purple/Magenta
+#--------------------------------------------------------------
+color5  #ED7782
+color13 #ED7782
+
+#--------------------------------------------------------------
+# Desaturated Cyan
+#--------------------------------------------------------------
+color6  #A2DAC6
+color14 #A2DAC6
+
+#--------------------------------------------------------------
+# Always show window title bar
+#--------------------------------------------------------------
+hide_window_decorations no
+
+#--------------------------------------------------------------
+# Sync to monitor to prevent screen tearing
+#--------------------------------------------------------------
+sync_to_monitor yes
+
+#--------------------------------------------------------------
+# Disable audio notification / error bell
+#--------------------------------------------------------------
+enable_audio_bell no
+EOF
+	chown "${SUDO_USER:=$USER}":"${SUDO_USER:=$USER}" /home/"${SUDO_USER:=$USER}"/.config/kitty/kitty.conf 2>/dev/null
 }
 
 #--------------------------------------------------------------
@@ -905,7 +1049,7 @@ URxvt.cursorBlink: true
 URxvt.geometry: 132x44
 URxvt.scrollBar: false
 URxvt.scrollBar_right: false
-URxvt.font: xft:Sarasa\ Mono\ CL\ Nerd\ Font:size=12, xft:Sarasa\ Mono\ CL:size=12
+URxvt.font: xft:Iosevka:size=12, xft:Sarasa\ Mono\ CL\ Nerd\ Font:size=12, xft:Sarasa\ Mono\ CL:size=12
 EOF
 	chown "${SUDO_USER:=$USER}":"${SUDO_USER:=$USER}" /home/"${SUDO_USER:=$USER}"/.Xresources 2>/dev/null
 }
@@ -2092,7 +2236,7 @@ volume-keys = volume
 terminal-cursor-blink-rate = 500
 
 ### Cursor style: block, bar, underline.
-terminal-cursor-style = block
+terminal-cursor-style = bar
 
 #--------------------------------------------------------------
 # Extra keys
@@ -2454,6 +2598,7 @@ dotfiles(){
 		echo -e "          $script_name --bash\n"
 		echo -e "Options: -b,  --bashrc   Add custom .bashrc"
 		echo -e "         -h,  --help     Print out this message"
+		echo -e "         -k,  --kitty    Add custom kitty.conf"
 		echo -e "         -m,  --mkshrc   Add custom mkshrc for android"
 		echo -e "         -te, --termux   Add custom colorscheme and prop files"
 		echo -e "         -tm, --tmux     Add custom .tmux.conf"
@@ -2482,6 +2627,16 @@ dotfiles(){
 				;;
 				-h | --help)
 					print_help
+				;;
+				-k | --kitty)
+					[[ $(type -p kitty) ]] && {
+						print_kitty "$@" &&
+						print_success "Finished updating '~/.config/kitty/kitty.conf'" ||
+						print_error "Failed to update '~/.config/kitty/kitty.conf'"
+						exit 0
+					}
+					print_missing_dependencies "kitty"
+					exit 1
 				;;
 				-m | --mkshrc)
 					[[ -d /system/app/ && -f /system/build.prop ]] && {
@@ -3433,7 +3588,7 @@ omaps-backup(){
 						print_error "No available backups"
 						exit 1
 					}
-					echo -e "\033[1;37mAvailable backups:\033[00m"
+					echo -e "\033[1;97mAvailable backups:\033[00m"
 					ls -A "$omaps_backup_dir"
 					exit 0
 				;;
@@ -3704,7 +3859,7 @@ opencamera-backup(){
 						print_error "No available backups"
 						exit 1
 					}
-					echo -e "\033[1;37mAvailable backups:\033[00m"
+					echo -e "\033[1;97mAvailable backups:\033[00m"
 					ls -A "$ocam_backup_dir"
 					exit 0
 				;;
@@ -4579,6 +4734,27 @@ EOF
 			# Create custom Xresources
 			print_xresources "$@"
 		}
+		install_kitty(){
+			# Update xbps and enable multi-lib repo
+			xbps-install -Syu xbps void-repo-multilib &&
+			xbps-install -Syu kitty
+			# Create vim file association
+			mkdir -p /home/"$SUDO_USER"/.local/share/applications || print_write_error "/home/"$SUDO_USER"/.local/share/applications"
+			chown -R "$SUDO_USER":"$SUDO_USER" /home/"$SUDO_USER"/.local/ 2>/dev/null
+			cat 2>/dev/null << "EOF" > /home/"$SUDO_USER"/.local/share/applications/vim.desktop
+[Desktop Entry]
+Version=1.0
+Name=vim
+Comment=Screen-based text editor program
+Exec=kitty -e vim %f
+Icon=kitty
+Type=Application
+MimeType=text/plain;
+EOF
+			chown "${SUDO_USER:=$USER}":"${SUDO_USER:=$USER}" /home/"${SUDO_USER:=$USER}"/.local/share/applications/vim.desktop 2>/dev/null
+			# Create custom Xresources
+			print_kitty "$@"
+		}
 	}
 	install_extras(){
 		# Disble ssh server
@@ -5152,7 +5328,7 @@ EOF
 			exit 1
 		}
 		# Handles Terminal Software Installation
-		echo -e "\nInstall Terminal: \n1.Urxvt \n2.Skip \n3.Exit\n"
+		echo -e "\nInstall Terminal: \n1.Urxvt \n2.Kitty \n3.Skip \n4.Exit\n"
 		read -rep "Select Terminal: " term_option
 		case "$term_option" in
 			1)
@@ -5164,10 +5340,17 @@ EOF
 			;;
 			2)
 				echo ""
+				print_warning "Installing Kitty\n"
+				install_terminal && install_kitty && error_check="terminal" &&
+				echo "" &&
+				print_success "Finished installing Kitty"
+			;;
+			3)
+				echo ""
 				print_warning "Skipping Terminal Installation"
 				error_check="terminal"
 			;;
-			3)
+			4)
 				run_on_exit
 			;;
 			-*)
@@ -5567,7 +5750,7 @@ tfetch(){
 		color_blue="\033[1;34m"
 		color_magenta="\033[1;35m"
 		color_cyan="\033[1;36m"
-		color_white="\033[1;37m"
+		color_white="\033[1;97m"
 		no_color="\033[00m"
 		# Fixes empty $USER in non-root termux
 		[[ -z $USER ]] && {
@@ -7258,7 +7441,7 @@ whatsapp-backup(){
 						print_error "No available backups"
 						exit 1
 					}
-					echo -e "\033[1;37mAvailable backups:\033[00m"
+					echo -e "\033[1;97mAvailable backups:\033[00m"
 					ls -A "$whatsapp_backup_dir"
 					exit 0
 				;;
@@ -7353,9 +7536,9 @@ tether(){
 		echo -e "         -l, --list     List all available functions"
 		echo -e "         -s, --silent   '-i/--install' with hidden output"
 		echo -e "         -V, --version  Show version information\n"
-		echo -e "\033[1;37m$script_name\033[00m is a multi-call shell script that combines many applets into a single executable."
-		echo -e "Create symbolic links to \033[1;37m$script_name\033[00m for each function and \033[1;37m$script_name\033[00m will act like whatever it was invoked as\n"
-		echo -e "\033[1;37mCurrently defined functions ($(req_func)):\033[00m"
+		echo -e "\033[1;97m$script_name\033[00m is a multi-call shell script that combines many applets into a single executable."
+		echo -e "Create symbolic links to \033[1;97m$script_name\033[00m for each function and \033[1;97m$script_name\033[00m will act like whatever it was invoked as\n"
+		echo -e "\033[1;97mCurrently defined functions ($(req_func)):\033[00m"
 		print_function_names
 		exit 0
 	}
@@ -7392,7 +7575,7 @@ tether(){
 					exit 0
 				;;
 				-l | --list)
-					echo -e "\033[1;37mCurrently defined functions ($(req_func)):\033[00m"
+					echo -e "\033[1;97mCurrently defined functions ($(req_func)):\033[00m"
 					print_function_names
 					exit 0
 				;;
